### PR TITLE
Dt 032313 reminders feature v6

### PR DESCRIPTION
**Pull request by AlexBestoso**
Adds reminders and expiration dates to the module

### CODE REVIEW

**Comment by AlexBestoso** [comment]
Looks like some extra files were changed...not sure why. Investigating.

~edit: changes are unrelated to my commit.

**Comment by jason-decisions** [comment]
v6 and v7 are very different in their build files. I would manually make whatever change you made in v7 in v6.

**Comment by AlexBestoso** [comment]
> v6 and v7 are very different in their build files. I would manually make whatever change you made in v7 in v6.

The changes I made were manual. I believe that this is due to the branch being stale

**Comment by jason-decisions** [comment]
No, the issue is that your PR is targeting a merge into "master" instead of 6x. You can change that.

**Comment by jason-decisions** [comment]
Edit the PR here 
image

Then change base to 6x
image

**Review by jason-decisions — APPROVED** [review]

**Review by jeff-decisions — APPROVED** [review]

**Pull request merged**
